sequenceDiagram
  participant participant_getSupabaseOAuthProviderDefinition as getSupabaseOAuthProviderDefinition
  participant participant_isSupabaseOAuthProviderId as isSupabaseOAuthProviderId
  participant_getSupabaseOAuthProviderDefinition->>participant_isSupabaseOAuthProviderId: isSupabaseOAuthProviderId()
  participant_isSupabaseOAuthProviderId-->>participant_getSupabaseOAuthProviderDefinition: return
