sequenceDiagram
  participant participant_getSupabaseOAuthProviderDefinition as getSupabaseOAuthProviderDefinition
  participant participant_isSupabaseOAuthProviderId as isSupabaseOAuthProviderId
  participant participant_validateSupabaseOAuthSecretPayload as validateSupabaseOAuthSecretPayload
  participant_validateSupabaseOAuthSecretPayload->>participant_getSupabaseOAuthProviderDefinition: getSupabaseOAuthProviderDefinition()
  participant_getSupabaseOAuthProviderDefinition->>participant_isSupabaseOAuthProviderId: isSupabaseOAuthProviderId()
  participant_isSupabaseOAuthProviderId-->>participant_getSupabaseOAuthProviderDefinition: return
  participant_getSupabaseOAuthProviderDefinition-->>participant_validateSupabaseOAuthSecretPayload: return
