graph TD
  package__ankhorage_supabase_auth["SUPABASE AUTH"]
  entrypoint_src_index_ts["src/index.ts"]
  package__ankhorage_supabase_auth --> entrypoint_src_index_ts
  module_src_createSupabaseAuthAdapter_ts["src/createSupabaseAuthAdapter.ts"]
  package__ankhorage_supabase_auth -.-> module_src_createSupabaseAuthAdapter_ts
  module_src_createSupabaseAuthAdapter_ts --> module_src_errors_ts
  module_src_createSupabaseAuthAdapter_ts --> module_src_oauth_ts
  module_src_createSupabaseAuthAdapter_ts --> module_src_oauthProviderDefinitions_ts
  module_src_createSupabaseAuthAdapter_ts --> module_src_session_ts
  module_src_createSupabaseAuthAdapter_ts --> module_src_types_ts
  module_src_errors_ts["src/errors.ts"]
  package__ankhorage_supabase_auth -.-> module_src_errors_ts
  module_src_errors_ts --> module_src_types_ts
  module_src_index_ts["src/index.ts"]
  module_src_oauth_ts["src/oauth.ts"]
  package__ankhorage_supabase_auth -.-> module_src_oauth_ts
  module_src_oauth_ts --> module_src_oauthProviderDefinitions_ts
  module_src_oauth_ts --> module_src_session_ts
  module_src_oauth_ts --> module_src_types_ts
  module_src_oauthProviderDefinitions_ts["src/oauthProviderDefinitions.ts"]
  package__ankhorage_supabase_auth -.-> module_src_oauthProviderDefinitions_ts
  module_src_session_ts["src/session.ts"]
  package__ankhorage_supabase_auth -.-> module_src_session_ts
  module_src_types_ts["src/types.ts"]
  package__ankhorage_supabase_auth -.-> module_src_types_ts
