import type {
  AuthOAuthErrorCode,
  AuthOAuthErrorStage,
  AuthOAuthProviderId,
  AuthSession,
} from '@ankhorage/contracts/auth';

export type SupabaseAuthFetch = typeof fetch;

export interface SupabaseAuthStorage {
  getItem(key: string): string | Promise<string | null> | null;
  setItem(key: string, value: string): void | Promise<void>;
  removeItem(key: string): void | Promise<void>;
}

export const SUPABASE_AUTH_PROFILE_FIELDS = [
  'email',
  'displayName',
  'avatarUrl',
  'username',
  'phone',
] as const;
export type SupabaseAuthProfileField = (typeof SUPABASE_AUTH_PROFILE_FIELDS)[number];

export interface SupabaseAuthProfileVerificationConfig {
  /** App-owned profile table generated by @ankhorage/infra. */
  table: string;
  /** Configured profile fields whose provider metadata should match when available. */
  fields?: readonly SupabaseAuthProfileField[];
  /** Number of reads used to allow the auth.users trigger to become visible through PostgREST. */
  maxAttempts?: number;
  /** Delay between profile reads. Use zero for deterministic tests. */
  retryDelayMs?: number;
}

export interface SupabaseOAuthProfileVerificationInput {
  correlationId: string;
  provider: AuthOAuthProviderId;
  session: AuthSession;
}

export type SupabaseOAuthProfileVerificationResult =
  | { ok: true }
  | { ok: false; message: string };

export type SupabaseOAuthProfileVerifier = (
  input: SupabaseOAuthProfileVerificationInput,
) => Promise<SupabaseOAuthProfileVerificationResult>;

export type SupabaseOAuthLifecycleStatus =
  | 'started'
  | 'cancelled'
  | 'error'
  | 'profile_verified'
  | 'authenticated';

export interface SupabaseOAuthLifecycleEvent {
  correlationId: string;
  provider: AuthOAuthProviderId;
  stage: AuthOAuthErrorStage;
  status: SupabaseOAuthLifecycleStatus;
  errorCode?: AuthOAuthErrorCode;
}

/**
 * Receives metadata-only OAuth lifecycle events. Events never contain callback URLs,
 * authorization codes, tokens, client secrets, private keys, or session payloads.
 */
export type SupabaseOAuthLifecycleObserver = (
  event: SupabaseOAuthLifecycleEvent,
) => void | Promise<void>;

export interface SupabaseAuthConfig {
  url: string;
  anonKey: string;
  fetch?: SupabaseAuthFetch;
  storage?: SupabaseAuthStorage;
  storageKey?: string;
  oauthProviders?: readonly AuthOAuthProviderId[];
  profileVerification?: SupabaseAuthProfileVerificationConfig;
  onOAuthLifecycleEvent?: SupabaseOAuthLifecycleObserver;
}

export type SupabaseAuthErrorCode =
  | 'invalid_credentials'
  | 'missing_identifier'
  | 'missing_password'
  | 'missing_refresh_token'
  | 'network_error'
  | 'provider_error'
  | 'session_expired'
  | 'session_persistence_failed'
  | 'unsupported_identifier'
  | 'validation_error';

export interface SupabaseProviderErrorCause {
  status?: number;
  body?: unknown;
}
